# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cross-stub}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["NgTzeYang"]
  s.date = %q{2010-10-16}
  s.description = %q{}
  s.email = %q{ngty77@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".infinity_test",
     "HISTORY.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cross-stub.gemspec",
     "lib/cross-stub.rb",
     "lib/cross-stub/arguments.rb",
     "lib/cross-stub/arguments/array.rb",
     "lib/cross-stub/arguments/hash.rb",
     "lib/cross-stub/arguments/proc.rb",
     "lib/cross-stub/cache.rb",
     "lib/cross-stub/fixes.rb",
     "lib/cross-stub/stores.rb",
     "lib/cross-stub/stores/base.rb",
     "lib/cross-stub/stores/file.rb",
     "lib/cross-stub/stores/memcache.rb",
     "lib/cross-stub/stores/redis.rb",
     "lib/cross-stub/stubber.rb",
     "rails_generators/cross_stub/cross_stub_generator.rb",
     "rails_generators/cross_stub/templates/config/initializers/cross-stub.rb",
     "rails_generators/cross_stub/templates/features/support/cross-stub.rb",
     "spec/.bacon",
     "spec/includes.rb",
     "spec/integration/clearing_instance_stubs_spec.rb",
     "spec/integration/clearing_stubs_spec.rb",
     "spec/integration/creating_instance_stubs_spec.rb",
     "spec/integration/creating_stubs_spec.rb",
     "spec/integration/shared_spec.rb",
     "spec/integration/stubbing_error_spec.rb",
     "spec/service.rb",
     "spec/spec_helper.rb",
     "tmp/.dummy"
  ]
  s.homepage = %q{http://github.com/ngty/cross-stub}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.6")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple cross process stubbing}
  s.test_files = [
    "spec/includes.rb",
     "spec/service.rb",
     "spec/integration/stubbing_error_spec.rb",
     "spec/integration/creating_instance_stubs_spec.rb",
     "spec/integration/shared_spec.rb",
     "spec/integration/clearing_stubs_spec.rb",
     "spec/integration/creating_stubs_spec.rb",
     "spec/integration/clearing_instance_stubs_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bacon>, [">= 0.0.0"])
      s.add_development_dependency(%q<otaku>, [">= 0.4.0"])
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 1.2.5"])
      s.add_runtime_dependency(%q<sexp_processor>, [">= 3.0.5"])
      s.add_runtime_dependency(%q<sourcify>, [">= 0.4.0"])
    else
      s.add_dependency(%q<bacon>, [">= 0.0.0"])
      s.add_dependency(%q<otaku>, [">= 0.4.0"])
      s.add_dependency(%q<ruby2ruby>, [">= 1.2.5"])
      s.add_dependency(%q<sexp_processor>, [">= 3.0.5"])
      s.add_dependency(%q<sourcify>, [">= 0.4.0"])
    end
  else
    s.add_dependency(%q<bacon>, [">= 0.0.0"])
    s.add_dependency(%q<otaku>, [">= 0.4.0"])
    s.add_dependency(%q<ruby2ruby>, [">= 1.2.5"])
    s.add_dependency(%q<sexp_processor>, [">= 3.0.5"])
    s.add_dependency(%q<sourcify>, [">= 0.4.0"])
  end
end

