# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cross-stub}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["NgTzeYang"]
  s.date = %q{2010-04-03}
  s.description = %q{}
  s.email = %q{ngty77@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cross-stub.gemspec",
     "lib/cross-stub.rb",
     "lib/cross-stub/cache_helpers.rb",
     "lib/cross-stub/pseudo_class.rb",
     "lib/cross-stub/setup_helpers.rb",
     "lib/cross-stub/stub_helpers.rb",
     "rails_generators/cross_stub/cross_stub_generator.rb",
     "rails_generators/cross_stub/templates/config/initializers/cross-stub.rb",
     "rails_generators/cross_stub/templates/features/support/cross-stub.rb",
     "spec/.bacon",
     "spec/cross-stub/clearing_stubs_spec.rb",
     "spec/cross-stub/creating_stubs_spec.rb",
     "spec/cross-stub/stubbing_error_spec.rb",
     "spec/helpers.rb",
     "spec/spec_helper.rb",
     "tmp/.dummy"
  ]
  s.homepage = %q{http://github.com/ngty/cross-stub}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple cross process stubbing}
  s.test_files = [
    "spec/helpers.rb",
     "spec/cross-stub/stubbing_error_spec.rb",
     "spec/cross-stub/clearing_stubs_spec.rb",
     "spec/cross-stub/creating_stubs_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bacon>, [">= 0.0.0"])
      s.add_development_dependency(%q<eventmachine>, [">= 0.0.0"])
      s.add_runtime_dependency(%q<ParseTree>, ["= 3.0.4"])
      s.add_runtime_dependency(%q<ruby2ruby>, ["= 1.2.4"])
    else
      s.add_dependency(%q<bacon>, [">= 0.0.0"])
      s.add_dependency(%q<eventmachine>, [">= 0.0.0"])
      s.add_dependency(%q<ParseTree>, ["= 3.0.4"])
      s.add_dependency(%q<ruby2ruby>, ["= 1.2.4"])
    end
  else
    s.add_dependency(%q<bacon>, [">= 0.0.0"])
    s.add_dependency(%q<eventmachine>, [">= 0.0.0"])
    s.add_dependency(%q<ParseTree>, ["= 3.0.4"])
    s.add_dependency(%q<ruby2ruby>, ["= 1.2.4"])
  end
end

